server:
 port: 8080
 error:
  include-binding-errors: always
  include-message: always
  include-stacktrace: never
  
spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/visionrent_db
  username: visionrent_user
  password: password
  driver-class-name: org.postgresql.Driver
 jpa:
  hibernate: 
   ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  properties:
   '[hibernate.format_sql]': true
 #image
 servlet:
  multipart:
   max-file-size: 2MB
   max-request-size: 2MB   
   
logging:
 file:
  name: log/visionrent.log
 pattern:
  file: "%d %-5level [%thread] %logger:%msg%n"
 level:
  '[org.springframework.web]' : WARN
  '[org.hibernate]' : INFO
  '[org.visionrent]' : DEBUG
  
management: #actuator
 endpoints:
  web:
   exposure:
    include: '*'
 info:
  env: 
   enabled: true
 endpoint:
  health:
   show-details: always
  shutdown:
   enabled: true 

visionrent:
 app:
  jwtSecret: visionRent@!23
  jwtExpirationMs: 86400000   
   
info:
 application:
  name: 'VisionRent Backend App'
  description: 'This is VisionRent CarRental Backend Project'
  version: '@project.version@'
   
